import Head from 'next/head'

function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>hello</div>
    </div>
  )
}

export default Home
